apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kestra
  pass_credentials_all: false
  password: ""
  url: https://helm.kestra.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: argo
  pass_credentials_all: false
  password: ""
  url: https://argoproj.github.io/argo-helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitwarden
  pass_credentials_all: false
  password: ""
  url: https://charts.bitwarden.com/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: metallb
  pass_credentials_all: false
  password: ""
  url: https://metallb.github.io/metallb
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: metrics-server
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/metrics-server/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kedacore
  pass_credentials_all: false
  password: ""
  url: https://kedacore.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana-community
  pass_credentials_all: false
  password: ""
  url: https://grafana-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: emberstack
  pass_credentials_all: false
  password: ""
  url: https://emberstack.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nvdp
  pass_credentials_all: false
  password: ""
  url: https://nvidia.github.io/k8s-device-plugin
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: gpu-helm-charts
  pass_credentials_all: false
  password: ""
  url: https://nvidia.github.io/dcgm-exporter/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nvidia
  pass_credentials_all: false
  password: ""
  url: https://nvidia.github.io/k8s-device-plugin
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: longhorn
  pass_credentials_all: false
  password: ""
  url: https://charts.longhorn.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ingress-nginx
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: stirling-pdf
  pass_credentials_all: false
  password: ""
  url: https://stirling-tools.github.io/Stirling-PDF-chart
  username: ""
